// 렌더 가시성 그룹(단일 출처) — 빌더가 push, applyVisibility가 visible 제어. 배열은 공유 참조(import해도 동일 객체).
export const firstFloorFinishObjects = []; // 집 1층 바닥재(바닥틀 위) — 1층 '1층 바닥' 토글
export const deckFloorObjects = [];   // 데크 포세린 바닥 + 데크 계단 디딤판 — 썬룸 '데크 바닥' 토글
export const firstFloorObjects = [];   // 1층 골조·실내(기초 토글 시 숨김)
export const bathObjects = [];         // 계단하부 WC(변기·세면대·온수기·배기) — '화장실' 토글
export const firstWallObjects = [];    // 1층 외벽(반투명, 두께 0.2·높이 2.4) — 1층·다락·지붕 단계에서 표시
export const firstDimObjects = [];     // 1층 방 안목치수(너비·깊이) — 방바닥에 표기, 1층·다락·지붕 단계에서 표시
export const secondFloorObjects = [];
export const roofObjects = [];
export const deckObjects = [];      // 데크 바닥·계단(데크 토글)
export const 썬룸Objects = [];   // 썬룸 구조물: 지붕·팬·조명·치수·외피(썬룸 토글)
export const 썬룸FrameObjects = []; // 썬룸 철골 골조: 기둥·보·평프레임(골조 토글 또는 썬룸 토글 중 하나라도 켜지면 표시)
export const wallObjects = [];      // 썬룸 외벽: 다누몰 자바라 폴딩창(외벽 토글 — 시공 업체 별도)
export const foldingObjects = [];   // 거실 데크 3면 폴딩도어(폴딩도어 토글 — 외벽과 상호배타)
export const extrasObjects = [];    // 소품: 의자·그릴·화분(전체일 때만 표시)
export const outletObjects = [];       // 전기 콘센트(1층) — 콘센트 토글
export const atticOutletObjects = [];  // 전기 콘센트(다락) — 콘센트 토글 + 다락 표시 시
export const hedgeObjects = [];        // 측백나무 생울타리(뒤·좌측) — 측백담장 토글
export const fenceObjects = [];        // 우측 콘크리트 담장(옆집 경계) — 옆집담장 토글
export const foundationObjects = [];   // 입체 기초(집+데크 시스템말뚝·두부, 높이 치수) — 바닥(평면도)에선 숨김
export const matFoundationHouseObjects = []; // 부분 매트기초 — 집만 50cm 콘크리트 매트 슬래브
export const matFoundationFullObjects = [];  // 전체 매트기초 — 집 + 데크 둘다 50cm 콘크리트 매트 슬래브
export const foundationDimObjects = []; // 기초 가로/세로 길이 치수 — 기초 뷰에서만(1층·다락·지붕에선 숨김)
export const footprintObjects = [];    // 집·데크 납작 발자국 — 현재 탭(설계안) 전용. 2층 탭에선 숨겨 집 배치도 분리(담장 발자국은 siteBaseObjects로 공통화).
export const planObjects = [];         // 바닥(평면도): 말뚝 마커 — 바닥에서만
export const dimObjects = [];          // 집·데크 크기 치수·모눈(8.5·4.0·데크) — 현재 탭 전용(바닥+기초)
export const planOnlyDimObjects = [];  // 평면 전용 치수(측백 0.5m) — 공통, 바닥에만, 기초 뷰에선 숨김
export const gapDimObjects = [];       // 집-담장 이격 치수(거실 0.5·뒤 1.0) — 공통(모든 탭), 바닥+기초
export const s2FootprintObjects = [];  // s2(2층·다락) 집 발자국(납작 8×6) — s2 탭 배치도에서만
export const s2FoundationObjects = []; // s2 기초(온통 0.5m 슬래브 8×6 + 높이 치수) — 's2 기초' 토글
export const s2DimObjects = [];        // s2 집 치수(너비 8·깊이 6) + 기준선 — s2 탭 배치도/기초
export const s2Wall1Objects = [];      // s2 외벽 1층(둘레 0.3m) — '외벽 1층' 토글
export const s2Wall2Objects = [];      // s2 외벽 2층(둘레 0.3m) — '외벽 2층' 토글
export const s2Wall3Objects = [];      // s2 외벽 3층(둘레 0.3m) — '외벽 3층' 토글
export const roofWallFBObjects = [];   // 박공 외벽 앞뒤(처마쪽, 기초 상단~처마) — '지붕' 그룹 '앞뒤' 토글
export const roofWallLRObjects = [];   // 박공 외벽 좌우(박공 삼각·꼭지점, 기초 상단~용마루) — '지붕' 그룹 '좌우' 토글
export const s2Stair2Objects = [];     // s2 계단2 공유부(라벨·각 층 바닥·층고 치수) — '계단' 버튼(전체) 연동
export const s2StairF1Objects = [];    // s2 계단2 1→2층 비행(하부런·참·상부런) — '1층>2층' 버튼 토글
export const s2StairF2Objects = [];    // s2 계단2 2→3층 비행(하부런·참·상부런) — '2층>3층' 버튼 토글
export const s2Floor1Objects = [];     // s2 1층 바닥 슬래브 — '바닥' 행 '1층' 버튼 토글
export const s2Floor2Objects = [];     // s2 2층 바닥 슬래브(계단실 구멍) — '바닥' 행 '2층' 버튼 토글
export const s2Floor3Objects = [];     // s2 3층 바닥 슬래브(계단실 구멍) — '바닥' 행 '3층' 버튼 토글
export const s2FrameObjects = [];       // s2 1층 골조(포치 개방 하중지지: 기둥·전이보·코어 전단벽) — 's2 골조' 토글
export const s2FurnitureObjects = [];   // s2 1층 가구(식탁·의자 라벨) — '1층 식탁·의자' 토글
export const s2SinkObjects = [];        // s2 1층 싱크대(주방) — '싱크대' 토글
export const s2StoveObjects = [];       // s2 1층 화목난로(오른쪽 붉은 예약 구획) — '난로' 버튼 토글
export const s2FoldingObjects = [];     // s2 1층 정면 폴딩도어(중앙 분리·양쪽 바깥 접힘, 가운데 두 짝 출입) — '폴딩도어' 토글
export const s2FrontStairObjects = [];  // s2 1층 정면 폴딩도어 앞 전체폭 계단(바닥→지면) — '계단' 토글
export const siteBaseObjects = [];   // 바탕 대지(흙)·도로 — 미검토 단계(1층·다락·지붕)에선 숨겨 빈 화면
export const deckStairFrameObjects = []; // 데크 계단틀(직선 앞·왼쪽 + 부채꼴 코너) — 바닥틀에서 분리, 썬룸 '데크계단틀' 토글
export const stairObjects = [];        // 계단 화면 전용 주석(거실·안방 크기·라벨·층고·다락바닥) — 계단 화면에서만 표시.
export const stairCoreObjects = [];    // ㄷ자 계단 본체(발판·사선·계단참) — 계단 화면 + 1층 화면 공유(계단에서 바꾸면 1층 반영).
export const stairWallObjects = [];    // 계단실 양쪽 세로 내벽(거실|계단실·계단실|안방) — 계단 화면 + 1층 화면 공유(1층 원래 벽 1벌). (구 단일 출처: 분리 후 livingInnerWallObjects·familyInnerWallObjects 사용)
export const livingInnerWallObjects = [];  // 거실|계단실 세로 내벽(비내력 10cm) — '거실측 벽' 부품 토글
export const familyInnerWallObjects = [];  // 계단실|안방 세로 내력벽(20cm) — '안방 내력벽' 부품 토글
